# Generated by Django 4.0.6 on 2022-07-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASDinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Age', models.IntegerField(max_length=8)),
                ('Question', models.CharField(max_length=2500)),
                ('Image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
