# Generated by Django 4.0.6 on 2022-07-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asdinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asdinfo',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
